CREATE SEQUENCE IF NOT EXISTS driver_details_seq
    START WITH 1
    INCREMENT BY 1; 

CREATE TABLE DriverDetails
(
    PRIMARY KEY (id),
    phoneNumber VARCHAR(15) NOT NULL,
    name VARCHAR(100) NOT NULL,
    vehicleType VARCHAR(50) NOT NULL,
    location VARCHAR(255) NOT NULL,
    assignID VARCHAR(50) NOT NULL,
    rate DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    area VARCHAR(100) NOT NULL,
    driverComments VARCHAR(255) DEFAULT '',

);
