project_id = "ride-backend-portfolio"
region     = "us-central1"
app_name   = "ride-driver-backend"
db_name    = "i-will-change-this-later"
db_user    = "i-will-change-this-later"
image      = "gcr.io/hibikiProject/hibikiApp:latest"