name: CI/CD to Google Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # To get OIDC token

    steps:
      - uses: actions/checkout@v6.0.0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v3 # To authenticate to Google Cloud using the OIDC token from Github Actions
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK for Docker authentication'
        id: 'setup-gcloud'
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          version: '>= 363.0.0'

      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet          

      - name: Build image
        run: |
          docker build -t us-central1-docker.pkg.dev/ride-backend-portfolio/ride-artifact-repository/ride-driver-backend:${{ github.sha }} .

      - name: Push image to Google Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/ride-backend-portfolio/ride-artifact-repository/ride-driver-backend:${{ github.sha }}

      - name: 'Deploy to Cloud Run'
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v3'
        with: 
          service: 'ride-driver-backend'
          image: 'us-central1-docker.pkg.dev/ride-backend-portfolio/ride-artifact-repository/ride-driver-backend:${{ github.sha }}'
          region: 'us-central1'
          flags: |-
            --allow-unauthenticated
            --service-account=${{ secrets.GCP_SERVICE_ACCOUNT }}
            --add-cloudsql-instances=ride-backend-portfolio:us-central1:ride-postgres-instance
            --vpc-connector=ride-vpc-connector
            --min-instances=0
            --max-instances=2
            --memory=512Mi
            --cpu=1
          env_vars: |-
             SPRING_PROFILES_ACTIVE=prod
             DB_PORT=5432
          secrets: |-
            DB_PASSWORD=db-password:latest
            DB_USERNAME=db-username:latest
            DB_HOST=db-host:latest
            DB_NAME=db-name:latest
            CLOUD_SQL_CONNECTION_NAME=cloud-sql-connection-name:latest
            JWT_SECRET_STRING=jwt-secret-string:latest
          env_vars_update_strategy: overwrite
          secrets_update_strategy: overwrite

      # - name: Deploy Cloud Run
      #   run: |
      #     gcloud run deploy my-backend \
      #       --image us-central1-docker.pkg.dev/ride-backend-portfolio/ride-backearide-artifact-repositorynd-portfolio/ride-driver-backend:${{ github.sha }} \
      #       --region us-central1 \
      #       --platform managed \
      #       --allow-unauthenticated \
      #       --service-account [SERVICE_ACCOUNT_NAME]@ride-backend-portfolio.iam.gserviceaccount.com